In [ ]:
#Simple Linear Regression

In [2]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [3]:
#import dataset
dataset= pd.read_csv('Salary_Data.csv')
x= dataset.iloc[:, :-1].values
y=dataset.iloc[:, 1].values

In [12]:
#splitting the dataset to test and training sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train ,y_test= train_test_split(x,y, test_size=1/3, random_state=0)

In [13]:
x_train

array([[ 9.6],
       [ 4. ],
       [ 5.3],
       [ 7.9],
       [ 2.9],
       [ 5.1],
       [ 3.2],
       [ 4.5],
       [ 8.2],
       [ 6.8],
       [ 1.3],
       [10.5],
       [ 3. ],
       [ 2.2],
       [ 5.9],
       [ 6. ],
       [ 3.7],
       [ 3.2],
       [ 9. ],
       [ 2. ],
       [ 1.1],
       [ 7.1],
       [ 4.9],
       [ 4. ]])

In [14]:
x_test

array([[ 1.5],
       [10.3],
       [ 4.1],
       [ 3.9],
       [ 9.5],
       [ 8.7]])

In [15]:
y_train

array([112635.,  55794.,  83088., 101302.,  56642.,  66029.,  64445.,
        61111., 113812.,  91738.,  46205., 121872.,  60150.,  39891.,
        81363.,  93940.,  57189.,  54445., 105582.,  43525.,  39343.,
        98273.,  67938.,  56957.])

In [17]:
#fitting simple linearregression to the training set
from sklearn.linear_model import LinearRegression
regression=LinearRegression()
regression.fit(x_train, y_train)

LinearRegression()

In [18]:
#predicting the test set results
y_pred=regression.predict(x_test)

In [19]:
y_test

array([ 37731., 122391.,  57081.,  63218., 116969., 109431.])

In [21]:
y_pred=regression.predict([[9.4]])

In [22]:
y_pred

array([114318.30534188])

In [ ]:
#visualizing the train set results
plt.scatter(x_train, y_train, color='red')
plt.plot(x_train, regression.predict(x_train), color='blue')
plt.title('salary vs experience(training set)')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.show()

In [ ]:
#visualizing the test set results
plt.scatter(x_test, y_test, color='red')
plt.plot(x_train, regression.predict(x_train), color='blue')
plt.title('salary vs experience(test set)')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.show()